version: v0.5.0
mode: python
release_tag_format: '{package}-v{version}'
generate:
  image: us-central1-docker.pkg.dev/cloud-sdk-librarian-prod/images-prod/python-librarian-generator:latest
  googleapis: 97763d6efb2d35474e0363c254ee6994837a08fa
  discovery: d4685cbda13fb10181e337531fcbca335beb1107
