librarian:
  version: v0.5.0
  language: python
  release_tag_format: '{id}-v{version}'
sources:
  googleapis: https://github.com/googleapis/googleapis/archive/97763d6efb2d35474e0363c254ee6994837a08fa.tar.gz
  discovery: https://github.com/googleapis/discovery-artifact-manager/archive/d4685cbda13fb10181e337531fcbca335beb1107.tar.gz
  protobuf: https://github.com/protocolbuffers/protobuf/releases/download/v29.3/protobuf-29.3.tar.gz
container:
  url: us-central1-docker.pkg.dev/cloud-sdk-librarian-prod/images-prod/python-librarian-generator
  version: latest
